# Generated by Django 5.2.5 on 2025-08-21 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('name', models.CharField(max_length=60)),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GroupDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('bool', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=25)),
                ('startTime', models.DateField()),
                ('finishTime', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('inProgress', models.BooleanField(default=None, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='centerapp.course')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='centerapp.groupday')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='centerapp.status')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('middleName', models.CharField(max_length=40)),
                ('year', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centerapp.groupstudent')),
            ],
        ),
        migrations.CreateModel(
            name='RatingStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('rating', models.CharField(max_length=3, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centerapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='RateStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('bool', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=200, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='centerapp.groupstudent')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centerapp.months')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centerapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='PayStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('text', models.CharField(max_length=200, null=True)),
                ('money', models.CharField(max_length=9, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centerapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=25)),
                ('middleName', models.CharField(max_length=25)),
                ('year', models.DateField(null=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centerapp.teacher'),
        ),
        migrations.CreateModel(
            name='VisitStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centerapp.student')),
            ],
        ),
    ]
